version: "3.7"

services:
    thingsboard:
        image: ivanmorenoj/thingsboard:v3.2.2
        ports:
            - 9090:9090
            - 1883:1883
            - 5683:5683/udp
        secrets:
            - psql-passw
        environment:
            - PG_HOST=db-postgres
            - PG_USER=thingsboard
            - PG_PASS_FILE=/run/secrets/psql-passw
        networks:
            - frontend
            - backend
        volumes:
            - thingsboard-data:/data
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
        
    db-postgres:
        image: postgres:12-alpine
        secrets:
            - psql-passw
        environment:
            - POSTGRES_USER=thingsboard
            - POSTGRES_DB=thingsboard 
            - POSTGRES_PASSWORD_FILE=/run/secrets/psql-passw
        networks:
            - backend
        volumes:
            - postgres-data:/var/lib/postgresql/data
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure

networks:
    frontend:
    backend:

volumes:
    postgres-data:
    thingsboard-data:

secrets:
    psql-passw:
        external: true
